##### https://kubernetes.io/docs/tasks/administer-cluster/namespaces/
---
apiVersion: v1
kind: Namespace
metadata:
  name: kong-appgw
  labels:
    app: kong-appgw

##### ConfigMap #####
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-configmap
  namespace: kong-appgw
data:
  cassandra_contact_point: "cassandra"
  cassandra_data_center: "k8sDataCenter"
  cassandra_rack_name: "KongK8sRack"
  cassandra_cluster_name: "KongCassandra"
  cassandra_seeds: "cassandra-0.cassandra.kong-appgw.svc.cluster.local,cassandra-1.cassandra.kong-appgw.svc.cluster.local,cassandra-2.cassandra.kong-appgw.svc.cluster.local"
  cassandra_auto_bootstrap: "false"
  cassandra_max_heap_size: 2048M
  cassandra_heap_newsize: 512M
  cassandra_user: "kong"
  cassandra_keyspace: "kong"
  galera_mariadb_host: "mariadb"
  galera_mariadb_port: "3306"
  galera_mariadb_cluster_name: "galera-mariadb"
  galera_mariadb_discovery_service: "etcd-client:2379"
  galera_mariadb_db_name: "konga_database"
  galera_mariadb_admin: "root"
  galera_mariadb_user: "kong"
  kong_database: "cassandra"
  kong_cassandra_replicas_factor: "3"
  kong_proxy_listen: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
  kong_admin_listen: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
  konga_node_env: "production"
  konga_token_secret: "km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb"
  konga_db_adapter: "mysql"
  konga_db_database: "konga_database"
  konga_db_uri: "mysql://kong:kong@mariadb:3306/konga_database"

##### Secret for store password with base64 #####
---
apiVersion: v1
kind: Secret
metadata:
  name: kong-secrets
  namespace: kong-appgw
data:
  # password (base64): echo -n 'kong' | base64
  cassandra_pass: a29uZw==
  # Root password (base64): echo -n 'apirath' | base64
  galera_mariadb_root_pass: YXBpcmF0aA==
  # backup password (base64): echo -n 'password' | base64
  galera_mariadb_xtrabackup_passwd: cGFzc3dvcmQ=
  # password (base64): echo -n 'kong' | base64
  galera_mariadb_pass: a29uZw==
