# ##### Mariadb Galera Cluster LoadBalancer Service #####
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mariadb-lb
#   labels:
#     app: mariadb-lb
#   namespace: kong-appgw
# spec:
#   type: LoadBalancer
#   loadBalancerSourceRanges:
#   - 0.0.0.0/0
#   ports:
#   - name: mariadb-lb
#     port: 13306
#     targetPort: 3306
#     protocol: TCP
#   selector:
#     app: mariadb

##### Mariadb Galera Cluster Service #####
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
  namespace: kong-appgw
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: mariadb

##### Mariadb Galera Cluster StatefulSet Template #####
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: kong-appgw
spec:
  serviceName: "mariadb"
  replicas: 3
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: labdocker/galara-mariadb:10.1
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: galera_mariadb_cluster_name
        - name: DISCOVERY_SERVICE
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: galera_mariadb_discovery_service
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-secrets
              key: galera_mariadb_root_pass
        - name: XTRABACKUP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-secrets
              key: galera_mariadb_xtrabackup_passwd
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: galera_mariadb_db_name
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: galera_mariadb_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-secrets
              key: galera_mariadb_pass
        readinessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --readiness
          initialDelaySeconds: 180
          periodSeconds: 1
        livenessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --liveness
          initialDelaySeconds: 210
          periodSeconds: 1
        volumeMounts:
        - name: mysql-datadir
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-datadir
      annotations:
        volume.beta.kubernetes.io/storage-class: gcp-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName: gcp-storage
      resources:
        requests:
          storage: 10Gi

##### phpMyadmin Service #####
---
apiVersion: v1
kind: Service
metadata:
  name: myadmin
  labels:
    app: myadmin
  namespace: kong-appgw
spec:
  ports:
  - port: 80
    name: mysql
  clusterIP: None
  selector:
    app: myadmin
# ##### phpMyadmin external Service #####
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: myadmin-lb
#   namespace: kong-appgw
# spec:
#   type: LoadBalancer
#   loadBalancerSourceRanges:
#   - 0.0.0.0/0
#   ports:
#   - name: myadmin-lb-ui
#     port: 80
#     targetPort: 80
#     protocol: TCP
#   selector:
#     app: myadmin
##### phpMyadmin #####
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myadmin
  namespace: kong-appgw
spec:
  replicas: 2
  template:
    metadata:
      name: myadmin
      labels:
        app: myadmin
    spec:
      containers:
      - name: myadmin-rc
        image: phpmyadmin/phpmyadmin:latest
        env:
        - name: PMA_ARBITRARY
          value: "1"
        - name: PMA_HOST
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: galera_mariadb_host
        - name: PMA_PORT
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: galera_mariadb_port
        - name: PMA_USER
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: galera_mariadb_admin
        - name: PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-secrets
              key: galera_mariadb_root_pass
        ports:
        - name: myadmin-ui
          containerPort: 80
          protocol: TCP
