apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration-cassandra
  namespace: kong-cluster
spec:
  template:
    metadata:
      name: kong-migration-cassandra
    spec:
      containers:
      - name: kong-migration-cassandra
        image: kong
        env:
          - name: KONG_NGINX_DAEMON
            value: 'off'
          - name: KONG_DATABASE
            value: cassandra
          - name: KONG_CASSANDRA_CONTACT_POINTS
            value: cassandra
          - name: KONG_CASSANDRA_KEYSPACE
            value: kong
          - name: KONG_CASSANDRA_USER
            value: kong
          - name: KONG_CASSANDRA_PASSWORD
            value: kong
        command: [ "/bin/sh", "-c", "kong migrations up" ]
      restartPolicy: Never
