apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration-cassandra
  namespace: kong-appgw
spec:
  template:
    metadata:
      name: kong-migration-cassandra
    spec:
      containers:
      - name: kong-migration-cassandra
        image: apirath/kong-appgw:v0.14.1-alpine
        env:
        - name: KONG_NGINX_DAEMON
          value: 'off'
        - name: KONG_DATABASE
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: kong_database
        - name: KONG_CASSANDRA_CONTACT_POINTS
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: cassandra_contact_point
        - name: KONG_CASSANDRA_KEYSPACE
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: cassandra_keyspace
        - name: KONG_CASSANDRA_USER
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: cassandra_user
        - name: KONG_CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-secrets
              key: cassandra_pass
        - name: KONG_CASSANDRA_REPL_FACTOR
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: kong_cassandra_replicas_factor
        command:
          - "/bin/sh"
          - "-c"
          - "kong migrations up"
      restartPolicy: Never
