apiVersion: batch/v1
kind: Job
metadata:
  name: konga-prepare
spec:
  template:
    metadata:
      name: konga-prepare
    spec:
      containers:
      - name: konga-prepare
        image: pantsel/konga:next
        # command: [ "/bin/bash", "start.sh", "-c", "prepare", "-a", "postgres", "-u", "postgresql://kong:kong@postgres:5432/konga_database" ]
        # command: [ "/bin/bash", "start.sh", "-c", "prepare", "-a", "mongo", "-u", "mongodb://kong:kong@mongo1:27017,mongo2:27017,mongo3:27017/konga_database" ]
        command: [ "/bin/bash", "start.sh", "-c", "prepare", "-a", "mysql", "-u", "mysql://kong:kong@mariadb:3306/konga_database" ]
      restartPolicy: Never
