apiVersion: batch/v1
kind: Job
metadata:
  name: konga-prepare
  namespace: kong-appgw
spec:
  template:
    metadata:
      name: konga-prepare
    spec:
      containers:
      - name: konga-prepare
        image: pantsel/konga:next
        command:
          - "/bin/bash"
          - "start.sh"
          - "-c prepare"
          - "-a mysql"
          - "-u ${DB_URI)"
        env:
        - name: DB_URI
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: konga_db_uri
      restartPolicy: Never
