##### Kong external Service #####
---
apiVersion: v1
kind: Service
metadata:
  name: kong-lb
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: kong-proxy-redirect-lb
    port: 80
    targetPort: 80
    protocol: TCP
  # - name: kong-proxy-lb
  #   port: 8000
  #   targetPort: 8000
  #   protocol: TCP
  - name: kong-proxy-ssl-lb
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: kong

##### Kong internal Service #####
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kong
  name: kong
spec:
  clusterIP: None
  ports:
    # - name: kong-proxy-redirect
    #   port: 80
    #   targetPort: 80
    #   protocol: TCP
    - name: kong-proxy
      port: 8000
      targetPort: 8000
      protocol: TCP
    # - name: kong-proxy-ssl
    #   port: 8443
    #   targetPort: 8443
    #   protocol: TCP
    - name: kong-admin
      port: 8001
      targetPort: 8001
      protocol: TCP
    - name: kong-admin-ssl
      port: 8444
      targetPort: 8444
      protocol: TCP
  selector:
    app: kong

# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: kong-nginx-conf
# spec:
#   template:
#     metadata:
#       name: kong-nginx-conf
#     spec:
#       containers:
#       - name: kong-nginx-conf
#         image:
#         command: [ "echo", '-e', 'server {\n    listen 80 default_server;\n    listen [::]:80 default_server;\n    server_name _;\n    return 301 https://$host$request_uri\;\n}', '>', "/usr/local/kong/nginx-include.conf" ]

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: kong
        env:
          - name: KONG_PROXY_LISTEN
            value: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
          - name: KONG_ADMIN_LISTEN
            value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
          - name: KONG_DATABASE
            value: cassandra
          - name: KONG_CASSANDRA_CONTACT_POINTS
            value: cassandra
          - name: KONG_CASSANDRA_KEYSPACE
            value: kong
          - name: KONG_CASSANDRA_USER
            value: kong
          - name: KONG_CASSANDRA_PASSWORD
            value: kong
          - name: KONG_CASSANDRA_REPL_FACTOR
            value: "2"
          - name: KONG_PROXY_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_ADMIN_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_PROXY_ERROR_LOG
            value: "/dev/stderr"
          - name: KONG_ADMIN_ERROR_LOG
            value: "/dev/stderr"
          # - name: KONG_NGINX_HTTP_INCLUDE
          #   value: "/usr/local/kong/nginx-include.conf"
        ports:
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: admin-ssl
          containerPort: 8444
          protocol: TCP
        - name: proxy-redirect
          containerPort: 80
          protocol: TCP
