##### Kong external Service #####
---
apiVersion: v1
kind: Service
metadata:
  name: kong-lb
  namespace: kong-appgw
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: kong-proxy-redirect-lb
    port: 80
    targetPort: 80
    protocol: TCP
  # - name: kong-proxy-lb
  #   port: 8000
  #   targetPort: 8000
  #   protocol: TCP
  - name: kong-proxy-ssl-lb
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: kong

##### Kong internal Service #####
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kong
  name: kong
  namespace: kong-appgw
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  # - name: kong-proxy-redirect
  #   port: 80
  #   targetPort: 80
  #   protocol: TCP
  - name: kong-proxy
    port: 8000
    targetPort: 8000
    protocol: TCP
  # - name: kong-proxy-ssl
  #   port: 443
  #   targetPort: 443
  #   protocol: TCP
  - name: kong-admin
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: kong-admin-ssl
    port: 8444
    targetPort: 8444
    protocol: TCP
  selector:
    app: kong

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong
  namespace: kong-appgw
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong-rc
        # image: kong
        image: apirath/kong-appgw:latest
        env:
        - name: KONG_PROXY_LISTEN
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: kong_proxy_listen
        - name: KONG_ADMIN_LISTEN
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: kong_admin_listen
        - name: KONG_DATABASE
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: kong_database
        - name: KONG_CASSANDRA_CONTACT_POINTS
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: cassandra_contact_point
        - name: KONG_CASSANDRA_KEYSPACE
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: cassandra_keyspace
        - name: CASSANDRA_USER
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: cassandra_user
        - name: CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-secrets
              key: cassandra_pass
        - name: KONG_CASSANDRA_REPL_FACTOR
          value: "2"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        # - name: KONG_NGINX_HTTP_INCLUDE
        #   value: "/usr/local/kong/nginx-include.conf"
        ports:
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: admin-ssl
          containerPort: 8444
          protocol: TCP
        - name: proxy-redirect
          containerPort: 80
          protocol: TCP
