##### Konga LoadBalancer Service #####
# ---
apiVersion: v1
kind: Service
metadata:
  name: konga-webui
  namespace: kong-appgw
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: konga-webui
    port: 80
    targetPort: 1337
    protocol: TCP
  # - name: konga-webui-ssl
  #   port: 443
  #   targetPort: 1337
  #   protocol: TCP
  selector:
    app: konga

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: konga
  namespace: kong-appgw
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga:next
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: konga_node_env
        - name: TOKEN_SECRET
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: konga_token_secret
        - name: DB_URI
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: konga_db_uri
        ports:
        - name: webui
          containerPort: 1337
          protocol: TCP
