##### Konga LoadBalancer Service #####
# ---
apiVersion: v1
kind: Service
metadata:
  name: konga-webui
  namespace: kong-appgw
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: konga-webui
    port: 80
    targetPort: 1337
    protocol: TCP
  # - name: konga-webui-ssl
  #   port: 443
  #   targetPort: 1337
  #   protocol: TCP
  selector:
    app: konga

# ##### Konga Service #####
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: konga
#   name: konga
#   namespace: kong-appgw
# spec:
#   clusterIP: None
#   ports:
#     - port: 1337
#   selector:
#     app: konga-rc

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: konga
  namespace: kong-appgw
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
      - name: konga-rc
        image: pantsel/konga:latest
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: konga_node_env
        - name: TOKEN_SECRET
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: konga_token_secret
        - name: DB_URI
          valueFrom:
            configMapKeyRef:
              name: kong-configmap
              key: konga_db_uri
        # - name: DB_ADAPTER
        #   valueFrom:
        #     configMapKeyRef:
        #       name: kong-configmap
        #       key: konga_db_adapter
        # - name: DB_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: kong-configmap
        #       key: galera_mariadb_host
        # - name: DB_PORT
        #   valueFrom:
        #     configMapKeyRef:
        #       name: kong-configmap
        #       key: galera_mariadb_port
        # - name: DB_USER
        #   valueFrom:
        #     configMapKeyRef:
        #       name: kong-configmap
        #       key: galera_mariadb_user
        # - name: DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: kong-secrets
        #       key: galera_mariadb_pass
        # - name: DB_DATABASE
        #   valueFrom:
        #     configMapKeyRef:
        #       name: kong-configmap
        #       key: konga_db_database
        ports:
        - name: webui
          containerPort: 1337
          protocol: TCP
