##### Konga LoadBalancer Service #####
---
apiVersion: v1
kind: Service
metadata:
  name: konga-webui
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: konga-webui
    port: 80
    targetPort: 1337
    protocol: TCP
  # - name: konga-webui-ssl
  #   port: 443
  #   targetPort: 1337
  #   protocol: TCP
  selector:
    app: konga

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: konga-rc
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: konga-rc
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga:next
        env:
          - name: DB_URI
            value: "mysql://kong:kong@mariadb:3306/konga_database"
          - name: DB_ADAPTER
            value: "mysql"
          - name: DB_HOST
            value: "mariadb"
          - name: DB_USER
            value: "kong"
          - name: DB_PASSWORD
            value: "kong"
          - name: TOKEN_SECRET
            value: "km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb"
          - name: DB_DATABASE
            value: "konga_database"
          - name: NODE_ENV
            value: "production"
        ports:
        - name: webui
          containerPort: 1337
          protocol: TCP
